apiVersion: v1
kind: PersistentVolume
metadata:
  name: sea-kaniko-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/sea-docker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sea-kaniko-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeName: sea-kaniko-pv
