Parameters:
    Prefix:
        Description: "Prefix of the project"
        Type: String
    EnvironmentName:
        Description: "Environment to deploy to."
        Type: String
    DomainName:
        Description: "Domain Name"
        Type: String
    SubDomainName:
        Description: "Sub Domain name"
        Type: String

Resources:
    001WebsitesS3BucketsStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
                !Sub "https://s3.amazonaws.com/${Prefix}-stacks/001WebsitesS3Buckets.cf.yaml"
            Parameters:
                Prefix: !Ref Prefix
                EnvironmentName: !Ref EnvironmentName
                DomainName: !Ref DomainName
                SubDomainName: !Ref SubDomainName
