apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret-tls
  namespace: default
data:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIJAL5m1Z2v3k4OMA0GCSqGSIb3DQEBCwUAMIGVMQswCQYD
    ...
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7z5J6...
    ...
    -----END PRIVATE KEY-----
type: kubernetes.io/tls
